const phones = [

  // ── 2025 ─────────────────────────────────────────────────────────────────
  {
    id: "a06",
    name: "Galaxy A06",
    year: 2025,
    price: 2299,
    chipset: "Helio G85",
    display: "6.7\" LCD, 60Hz",
    ram: "4GB",
    storage: "128GB",
    battery: "5000mAh",
    camera: "50MP + 2MP",
    selfie: "8MP",
    fiveG: false,
    scores: { camera: 5, performance: 4, battery: 8, display: 4, value: 7 },
    verdict: "Decent",
    verdictColor: "yellow",
    pros: ["Affordable entry price", "Decent battery life", "128GB storage included"],
    cons: ["60Hz LCD feels dated", "Helio G85 is slow", "No 5G"],
    mrPointSays: "The A06 is Samsung's most affordable 2025 option. You get a big battery and decent storage but the 60Hz LCD and Helio G85 chip make everything feel sluggish. It's fine for basic calls and WhatsApp but don't expect more."
  },
  {
    id: "a07",
    name: "Galaxy A07",
    year: 2025,
    price: 2499,
    chipset: "Helio G85",
    display: "6.7\" LCD, 60Hz",
    ram: "4GB",
    storage: "128GB",
    battery: "5000mAh",
    camera: "50MP + 2MP",
    selfie: "8MP",
    fiveG: false,
    scores: { camera: 5, performance: 4, battery: 8, display: 4, value: 7 },
    verdict: "Decent",
    verdictColor: "yellow",
    pros: ["128GB storage at entry price", "Big 5000mAh battery", "Affordable 2025 model"],
    cons: ["60Hz LCD feels dated", "Helio G85 is slow", "No 5G"],
    mrPointSays: "The A07 slots just above the A06 with the same core hardware but a slightly higher price tag. Battery life is its main selling point. It does the basics well, but don't expect speed or a great camera experience."
  },
  {
    id: "a16",
    name: "Galaxy A16",
    year: 2025,
    price: 3499,
    chipset: "Helio G99",
    display: "6.7\" Super AMOLED, 90Hz",
    ram: "4GB",
    storage: "128GB",
    battery: "5000mAh",
    camera: "50MP + 5MP + 2MP",
    selfie: "13MP",
    fiveG: false,
    scores: { camera: 6, performance: 6, battery: 8, display: 7, value: 7 },
    verdict: "Good Pick",
    verdictColor: "green",
    pros: ["Super AMOLED at this price is rare", "Helio G99 handles daily use well", "Promised 6 years of updates"],
    cons: ["Only 4GB RAM", "No 5G", "No OIS on camera"],
    mrPointSays: "The A16 quietly punches above its weight. A Super AMOLED display under R4000 is genuinely impressive, and Samsung's 6-year update promise makes it a smart long-term buy for budget shoppers."
  },
  {
    id: "a17",
    name: "Galaxy A17",
    year: 2025,
    price: 3999,
    chipset: "Helio G99",
    display: "6.7\" Super AMOLED, 90Hz",
    ram: "4GB",
    storage: "128GB",
    battery: "5000mAh",
    camera: "50MP + 5MP + 2MP",
    selfie: "13MP",
    fiveG: false,
    scores: { camera: 6, performance: 6, battery: 8, display: 7, value: 7 },
    verdict: "Good Pick",
    verdictColor: "green",
    pros: ["Super AMOLED under R4000", "Helio G99 handles everyday tasks", "13MP selfie at this price"],
    cons: ["No 5G", "Only 4GB RAM", "A16 offers near-identical value for less"],
    mrPointSays: "The A17 sits right between the A16 and A26 5G — same AMOLED quality, same Helio G99, but without 5G. If you find it discounted, it's solid. Otherwise the A16 at R3,499 offers almost the same phone for less money."
  },
  {
    id: "a26-5g",
    name: "Galaxy A26 5G",
    year: 2025,
    price: 4999,
    chipset: "Exynos 1380",
    display: "6.7\" Super AMOLED, 120Hz",
    ram: "8GB",
    storage: "128GB",
    battery: "5000mAh",
    camera: "50MP OIS + 12MP + 5MP",
    selfie: "13MP",
    fiveG: true,
    scores: { camera: 7, performance: 7, battery: 8, display: 8, value: 8 },
    verdict: "Great Buy",
    verdictColor: "green",
    pros: ["120Hz AMOLED looks stunning", "OIS on main camera", "5G + 8GB RAM at this price"],
    cons: ["Exynos 1380 can run warm", "No wireless charging", "Plastic build"],
    mrPointSays: "The A26 5G is where the 2025 A series starts getting genuinely exciting. 120Hz AMOLED, OIS, 8GB RAM, and 5G — all under R6500. Strong buy for anyone wanting a proper mid-ranger without breaking the bank."
  },
  {
    id: "a36-5g",
    name: "Galaxy A36 5G",
    year: 2025,
    price: 7999,
    chipset: "Snapdragon 6 Gen 3",
    display: "6.7\" Super AMOLED, 120Hz",
    ram: "8GB",
    storage: "256GB",
    battery: "5000mAh",
    camera: "50MP OIS + 12MP + 5MP",
    selfie: "12MP",
    fiveG: true,
    scores: { camera: 8, performance: 8, battery: 8, display: 8, value: 8 },
    verdict: "Great Buy",
    verdictColor: "green",
    pros: ["Snapdragon 6 Gen 3 is fast and efficient", "Excellent cameras with OIS", "256GB storage included"],
    cons: ["Pushes into premium mid-range pricing", "No wireless charging", "Similar cameras to A26"],
    mrPointSays: "The A36 is the best all-round phone in the 2025 A series. Snapdragon 6 Gen 3 gives it a real performance edge, 256GB storage is generous, and the cameras are excellent. If you want the sweet spot, this is it."
  },
  {
    id: "a56-5g",
    name: "Galaxy A56 5G",
    year: 2025,
    price: 10999,
    chipset: "Exynos 1580",
    display: "6.7\" Super AMOLED, 120Hz",
    ram: "12GB",
    storage: "256GB",
    battery: "5000mAh",
    camera: "50MP OIS + 12MP + 5MP",
    selfie: "12MP",
    fiveG: true,
    scores: { camera: 8, performance: 9, battery: 8, display: 9, value: 7 },
    verdict: "Great Buy",
    verdictColor: "green",
    pros: ["Exynos 1580 is the fastest A series chip yet", "12GB RAM handles everything", "Near-flagship experience"],
    cons: ["Price is getting close to Galaxy S entry level", "No wireless charging", "Exynos gets hot under sustained load"],
    mrPointSays: "The A56 is Samsung's most capable A series phone ever. The Exynos 1580 and 12GB RAM make it feel like a proper flagship. At R12,999 you could stretch to a Galaxy S entry, but the A56 is still excellent value."
  },

  // ── 2024 ─────────────────────────────────────────────────────────────────
  {
    id: "a05",
    name: "Galaxy A05",
    year: 2024,
    price: 1899,
    chipset: "MediaTek Helio G85",
    display: "6.7\" LCD, 60Hz",
    ram: "4GB",
    storage: "64GB",
    battery: "5000mAh",
    camera: "50MP + 2MP",
    selfie: "8MP",
    fiveG: false,
    scores: { camera: 5, performance: 4, battery: 8, display: 4, value: 7 },
    verdict: "Skip It",
    verdictColor: "red",
    pros: ["Big 5000mAh battery", "Large screen for the price", "Affordable entry point"],
    cons: ["60Hz LCD feels dated", "Weak Helio G85 chip", "No 5G"],
    mrPointSays: "The A05 is the bare minimum. The battery keeps it alive all day, but the 60Hz LCD and Helio G85 chip make everything feel slow. The A06 is newer and better for just R300 more."
  },
  {
    id: "a05s",
    name: "Galaxy A05s",
    year: 2024,
    price: 2899,
    chipset: "Snapdragon 680",
    display: "6.7\" LCD, 90Hz",
    ram: "4GB",
    storage: "128GB",
    battery: "5000mAh",
    camera: "50MP + 2MP + 2MP",
    selfie: "13MP",
    fiveG: false,
    scores: { camera: 5, performance: 5, battery: 8, display: 5, value: 7 },
    verdict: "Decent",
    verdictColor: "yellow",
    pros: ["90Hz refresh rate at this price", "Snapdragon 680 is reliable", "Large storage"],
    cons: ["Still an LCD panel", "No 5G", "Camera is average at best"],
    mrPointSays: "The A05s is a small step up from the A05 — the Snapdragon 680 and 90Hz screen help day-to-day. It's fine for social media and calls. Just make sure you don't pay more than R2900 for it."
  },
  {
    id: "a15",
    name: "Galaxy A15",
    year: 2024,
    price: 3499,
    chipset: "MediaTek Helio G99",
    display: "6.5\" Super AMOLED, 90Hz",
    ram: "4GB",
    storage: "128GB",
    battery: "5000mAh",
    camera: "50MP + 5MP + 2MP",
    selfie: "13MP",
    fiveG: false,
    scores: { camera: 6, performance: 6, battery: 8, display: 7, value: 8 },
    verdict: "Good Pick",
    verdictColor: "green",
    pros: ["Super AMOLED screen at this price is rare", "Helio G99 handles daily tasks well", "Good value overall"],
    cons: ["No 5G", "4GB RAM is limiting", "Night camera is mediocre"],
    mrPointSays: "The A15 quietly punches above its weight. That AMOLED display under R3500 is the real headline — colours pop and it makes everything look better. The new A16 is slightly better but if you find the A15 on sale, snap it up."
  },
  {
    id: "a15-5g",
    name: "Galaxy A15 5G",
    year: 2024,
    price: 3799,
    chipset: "Dimensity 6100+",
    display: "6.5\" LCD, 90Hz",
    ram: "4GB",
    storage: "128GB",
    battery: "5000mAh",
    camera: "50MP + 2MP + 2MP",
    selfie: "5MP",
    fiveG: true,
    scores: { camera: 5, performance: 6, battery: 8, display: 5, value: 6 },
    verdict: "Think Twice",
    verdictColor: "yellow",
    pros: ["5G connectivity", "Good battery life", "Decent chip"],
    cons: ["Downgraded to LCD vs A15 4G", "Weak 5MP selfie", "Costs more for a worse screen"],
    mrPointSays: "Confusingly, the 5G version of the A15 has a worse screen than the standard A15. You're paying more and losing the AMOLED. Unless you desperately need 5G, stick with the regular A15 or wait for the A16."
  },
  {
    id: "a25-5g",
    name: "Galaxy A25 5G",
    year: 2024,
    price: 4499,
    chipset: "Exynos 1280",
    display: "6.5\" Super AMOLED, 120Hz",
    ram: "6GB",
    storage: "128GB",
    battery: "5000mAh",
    camera: "50MP OIS + 8MP + 2MP",
    selfie: "13MP",
    fiveG: true,
    scores: { camera: 7, performance: 7, battery: 8, display: 8, value: 8 },
    verdict: "Great Buy",
    verdictColor: "green",
    pros: ["120Hz AMOLED looks brilliant", "OIS on main camera helps a lot", "5G + solid performance"],
    cons: ["Exynos can run warm", "No wireless charging", "Plastic build"],
    mrPointSays: "This is where the A series starts getting genuinely good. The 120Hz AMOLED screen is smooth and vibrant, OIS makes your photos sharper, and 5G is included. The A26 is newer but if the A25 is heavily discounted, it's still a strong pick."
  },
  {
    id: "a35-5g",
    name: "Galaxy A35 5G",
    year: 2024,
    price: 5999,
    chipset: "Exynos 1380",
    display: "6.6\" Super AMOLED, 120Hz",
    ram: "6GB",
    storage: "128GB",
    battery: "5000mAh",
    camera: "50MP OIS + 8MP + 5MP",
    selfie: "13MP",
    fiveG: true,
    scores: { camera: 8, performance: 7, battery: 8, display: 8, value: 7 },
    verdict: "Great Buy",
    verdictColor: "green",
    pros: ["Excellent cameras with OIS", "Bright 120Hz AMOLED", "5 years software support"],
    cons: ["A36 is better for similar money now", "No wireless charging", "Exynos gets warm"],
    mrPointSays: "The A35 was the 2024 mid-range champion. The A36 has largely taken its crown, but if you find the A35 at a serious discount it's still a rock-solid phone with great cameras and display."
  },
  {
    id: "a55-5g",
    name: "Galaxy A55 5G",
    year: 2024,
    price: 8499,
    chipset: "Exynos 1480",
    display: "6.6\" Super AMOLED, 120Hz",
    ram: "8GB",
    storage: "128GB",
    battery: "5000mAh",
    camera: "50MP OIS + 12MP + 5MP",
    selfie: "32MP",
    fiveG: true,
    scores: { camera: 8, performance: 8, battery: 8, display: 9, value: 7 },
    verdict: "Great Buy",
    verdictColor: "green",
    pros: ["Best display in the 2024 A series", "32MP selfie camera is outstanding", "Near-flagship experience"],
    cons: ["A56 now exists for more money", "No wireless charging", "Exynos heat under load"],
    mrPointSays: "The A55 remains a fantastic phone. Stunning display, great cameras, solid performance. The A56 is the newer flagship A series option but at R8,262 the A55 is better value for most people."
  },

  // ── 2023 ─────────────────────────────────────────────────────────────────
  {
    id: "a14",
    name: "Galaxy A14",
    year: 2023,
    price: 2199,
    chipset: "MediaTek Helio G80",
    display: "6.6\" LCD PLS, 60Hz",
    ram: "4GB",
    storage: "64GB",
    battery: "5000mAh",
    camera: "50MP + 2MP + 2MP",
    selfie: "13MP",
    fiveG: false,
    scores: { camera: 5, performance: 4, battery: 7, display: 4, value: 6 },
    verdict: "Decent",
    verdictColor: "yellow",
    pros: ["Big battery", "Cheap price", "Decent selfie camera"],
    cons: ["Sluggish Helio G80", "60Hz LCD is dull", "Very basic experience"],
    mrPointSays: "The A14 does the basics. You can call, text, scroll. But the 60Hz LCD and Helio G80 make it feel like a budget phone from 3 years ago. Spend a bit more and get the A15 or A16."
  },
  {
    id: "a14-5g",
    name: "Galaxy A14 5G",
    year: 2023,
    price: 2699,
    chipset: "Dimensity 700",
    display: "6.6\" LCD, 90Hz",
    ram: "4GB",
    storage: "64GB",
    battery: "5000mAh",
    camera: "50MP + 2MP + 2MP",
    selfie: "13MP",
    fiveG: true,
    scores: { camera: 5, performance: 5, battery: 7, display: 5, value: 6 },
    verdict: "Decent",
    verdictColor: "yellow",
    pros: ["5G at a low price", "90Hz refresh rate", "Dimensity 700 is capable"],
    cons: ["LCD panel", "Limited storage", "Camera struggles in low light"],
    mrPointSays: "If 5G is your priority and budget is very tight, the A14 5G gets the job done. But the A16 is a better buy for daily use. Only consider this if you find it at a serious discount."
  },
  {
    id: "a34-5g",
    name: "Galaxy A34 5G",
    year: 2023,
    price: 5499,
    chipset: "Dimensity 1080",
    display: "6.6\" Super AMOLED, 120Hz",
    ram: "6GB",
    storage: "128GB",
    battery: "5000mAh",
    camera: "48MP OIS + 8MP + 5MP",
    selfie: "13MP",
    fiveG: true,
    scores: { camera: 7, performance: 7, battery: 8, display: 8, value: 7 },
    verdict: "Good Pick",
    verdictColor: "green",
    pros: ["Smooth 120Hz AMOLED", "Good daylight camera with OIS", "Solid all-rounder"],
    cons: ["Dimensity 1080 is showing its age", "A35 and A36 are better now", "No IP rating"],
    mrPointSays: "The A34 was excellent in its time but newer options have overtaken it. If you find it significantly cheaper than the A35, it's still a good deal. Don't pay full price for it in 2025."
  },
  {
    id: "a54-5g",
    name: "Galaxy A54 5G",
    year: 2023,
    price: 7499,
    chipset: "Exynos 1380",
    display: "6.4\" Super AMOLED, 120Hz",
    ram: "8GB",
    storage: "256GB",
    battery: "5100mAh",
    camera: "50MP OIS + 12MP + 5MP",
    selfie: "32MP",
    fiveG: true,
    scores: { camera: 8, performance: 7, battery: 9, display: 9, value: 7 },
    verdict: "Great Buy",
    verdictColor: "green",
    pros: ["Exceptional battery life", "Gorgeous compact AMOLED", "32MP selfie is outstanding"],
    cons: ["Exynos can throttle under load", "A55 and A56 exist now", "Heavy"],
    mrPointSays: "The A54 remains one of the best A series phones Samsung has made. The battery outlasts almost everything at this price and the display is premium. If you find it on sale, it's a bargain."
  },

  // ── 2022 ─────────────────────────────────────────────────────────────────
  {
    id: "a13",
    name: "Galaxy A13",
    year: 2022,
    price: 2299,
    chipset: "Exynos 850",
    display: "6.6\" LCD PLS, 60Hz",
    ram: "3GB",
    storage: "32GB",
    battery: "5000mAh",
    camera: "50MP + 5MP + 2MP + 2MP",
    selfie: "8MP",
    fiveG: false,
    scores: { camera: 5, performance: 3, battery: 7, display: 4, value: 5 },
    verdict: "Skip It",
    verdictColor: "red",
    pros: ["Large 5000mAh battery", "Quad camera setup (on paper)", "Cheap"],
    cons: ["Exynos 850 is painfully slow", "3GB RAM is not enough", "60Hz LCD looks washed out"],
    mrPointSays: "The A13 aged badly. The Exynos 850 was never fast, and 3GB RAM means apps constantly reload. The quad camera sounds good but the extra lenses are useless depth sensors. Avoid."
  },
  {
    id: "a33-5g",
    name: "Galaxy A33 5G",
    year: 2022,
    price: 3999,
    chipset: "Exynos 1280",
    display: "6.4\" Super AMOLED, 90Hz",
    ram: "6GB",
    storage: "128GB",
    battery: "5000mAh",
    camera: "48MP OIS + 8MP + 5MP + 2MP",
    selfie: "13MP",
    fiveG: true,
    scores: { camera: 7, performance: 6, battery: 8, display: 7, value: 7 },
    verdict: "Good Pick",
    verdictColor: "green",
    pros: ["OIS at this price was impressive for its time", "Solid 5000mAh battery", "Still holds up"],
    cons: ["Only 90Hz, not 120Hz", "Newer options offer more for similar money", "Exynos 1280 is mid-tier"],
    mrPointSays: "The A33 was great value in 2022 and still holds its own. Just make sure you're getting it well below the price of a new A26 — that's a much better phone for daily use today."
  },
  {
    id: "a53-5g",
    name: "Galaxy A53 5G",
    year: 2022,
    price: 4999,
    chipset: "Exynos 1280",
    display: "6.5\" Super AMOLED, 120Hz",
    ram: "6GB",
    storage: "128GB",
    battery: "5000mAh",
    camera: "64MP OIS + 12MP + 5MP + 5MP",
    selfie: "32MP",
    fiveG: true,
    scores: { camera: 7, performance: 6, battery: 8, display: 8, value: 7 },
    verdict: "Good Pick",
    verdictColor: "green",
    pros: ["64MP main camera with OIS is excellent", "Fantastic 32MP selfie camera", "120Hz AMOLED"],
    cons: ["Exynos 1280 throttles under load", "Showing its age in 2025", "Heavy"],
    mrPointSays: "The A53 still takes great photos and that selfie camera is hard to beat. If you're buying second-hand and the price is right (under R4000), it's a solid choice. Don't pay new price for it."
  },
  {
    id: "a52s-5g",
    name: "Galaxy A52s 5G",
    year: 2022,
    price: 4499,
    chipset: "Snapdragon 778G",
    display: "6.5\" Super AMOLED, 120Hz",
    ram: "6GB",
    storage: "128GB",
    battery: "4500mAh",
    camera: "64MP OIS + 12MP + 5MP + 5MP",
    selfie: "32MP",
    fiveG: true,
    scores: { camera: 8, performance: 8, battery: 7, display: 8, value: 7 },
    verdict: "Great Buy",
    verdictColor: "green",
    pros: ["Snapdragon 778G is genuinely fast", "Excellent cameras", "Smooth 120Hz AMOLED"],
    cons: ["Smaller battery than most A series", "Getting old now", "Hard to find new"],
    mrPointSays: "The A52s is still one of the best A series phones ever made. The Snapdragon 778G gave it a performance edge the Exynos versions couldn't match. Find it second-hand and you've got a bargain."
  },
  {
    id: "a73-5g",
    name: "Galaxy A73 5G",
    year: 2022,
    price: 6499,
    chipset: "Snapdragon 778G",
    display: "6.7\" Super AMOLED, 120Hz",
    ram: "8GB",
    storage: "256GB",
    battery: "5000mAh",
    camera: "108MP OIS + 12MP + 5MP + 5MP",
    selfie: "32MP",
    fiveG: true,
    scores: { camera: 9, performance: 8, battery: 8, display: 8, value: 7 },
    verdict: "Great Buy",
    verdictColor: "green",
    pros: ["108MP camera is incredible for the price", "Snapdragon 778G performance", "Large 6.7\" AMOLED"],
    cons: ["Discontinued — hard to find new", "Big and heavy", "No 3.5mm jack"],
    mrPointSays: "The A73 was the king of the A series in 2022. That 108MP camera still impresses today. Hunt it down second-hand — it's worth it."
  },

  // ── 2021 ─────────────────────────────────────────────────────────────────
  {
    id: "a52",
    name: "Galaxy A52",
    year: 2021,
    price: 3999,
    chipset: "Snapdragon 720G",
    display: "6.5\" Super AMOLED, 90Hz",
    ram: "6GB",
    storage: "128GB",
    battery: "4500mAh",
    camera: "64MP OIS + 12MP + 5MP + 5MP",
    selfie: "32MP",
    fiveG: false,
    scores: { camera: 7, performance: 6, battery: 7, display: 8, value: 7 },
    verdict: "Good Pick",
    verdictColor: "green",
    pros: ["64MP OIS camera still excellent", "IP67 water resistance", "3.5mm headphone jack"],
    cons: ["Only 90Hz not 120Hz", "Snapdragon 720G starting to show its age", "No 5G"],
    mrPointSays: "The A52 is a classic. IP67 water resistance and OIS cameras at a mid-range price. Getting old now but a bargain second-hand. One of Samsung's best value phones ever made."
  },
  {
    id: "a72",
    name: "Galaxy A72",
    year: 2021,
    price: 5499,
    chipset: "Snapdragon 720G",
    display: "6.7\" Super AMOLED, 90Hz",
    ram: "6GB",
    storage: "128GB",
    battery: "5000mAh",
    camera: "64MP OIS + 12MP + 8MP + 5MP",
    selfie: "32MP",
    fiveG: false,
    scores: { camera: 7, performance: 6, battery: 9, display: 8, value: 7 },
    verdict: "Good Pick",
    verdictColor: "green",
    pros: ["Massive battery that goes for days", "IP67 water resistance", "Versatile quad camera"],
    cons: ["No 5G at this price point", "Only 90Hz display", "Heavy"],
    mrPointSays: "The A72 is an underrated battery champion. Two days of screen time was achievable and the cameras covered wide, telephoto and macro. Ideal for heavy users who hate charging."
  },
  {
    id: "a32",
    name: "Galaxy A32",
    year: 2021,
    price: 3299,
    chipset: "MediaTek Helio G80",
    display: "6.4\" Super AMOLED, 90Hz",
    ram: "4GB",
    storage: "128GB",
    battery: "5000mAh",
    camera: "64MP + 8MP + 5MP + 5MP",
    selfie: "20MP",
    fiveG: false,
    scores: { camera: 6, performance: 5, battery: 8, display: 7, value: 7 },
    verdict: "Decent",
    verdictColor: "yellow",
    pros: ["AMOLED screen at a low price", "Large battery", "64MP camera"],
    cons: ["Helio G80 is weak for this price", "No OIS on camera", "4GB RAM not ideal"],
    mrPointSays: "The A32 got an AMOLED display at a price where most competitors had LCD. The processor was always its weak point but general use was fine. A reasonable second-hand pick today."
  },
  {
    id: "a51",
    name: "Galaxy A51",
    year: 2021,
    price: 2699,
    chipset: "Exynos 9611",
    display: "6.5\" Super AMOLED, 60Hz",
    ram: "4GB",
    storage: "128GB",
    battery: "4000mAh",
    camera: "48MP + 12MP + 5MP + 5MP",
    selfie: "32MP",
    fiveG: false,
    scores: { camera: 7, performance: 5, battery: 6, display: 7, value: 6 },
    verdict: "Decent",
    verdictColor: "yellow",
    pros: ["Beautiful AMOLED display", "Great selfie camera", "Slim design"],
    cons: ["60Hz — no high refresh rate", "Battery is too small", "Exynos 9611 is slow now"],
    mrPointSays: "The A51 was a bestseller but it has aged hard. The 60Hz screen and 4000mAh battery are its biggest weaknesses. The selfie camera is still very good. Only worth it as a cheap second-hand deal under R2500."
  },
  {
    id: "a71",
    name: "Galaxy A71",
    year: 2021,
    price: 4499,
    chipset: "Snapdragon 730",
    display: "6.7\" Super AMOLED, 60Hz",
    ram: "6GB",
    storage: "128GB",
    battery: "4500mAh",
    camera: "64MP + 12MP + 5MP + 5MP",
    selfie: "32MP",
    fiveG: false,
    scores: { camera: 7, performance: 6, battery: 7, display: 8, value: 6 },
    verdict: "Decent",
    verdictColor: "yellow",
    pros: ["Large gorgeous AMOLED", "64MP camera holds up", "Snapdragon 730 still decent"],
    cons: ["60Hz screen is a letdown at this price", "No 5G", "Battery average for the size"],
    mrPointSays: "The A71 had a stunning screen but Samsung held back with a 60Hz panel at a price where competitors offered 90Hz. Still capable second-hand, but better options exist."
  },

  // ── 2020 ─────────────────────────────────────────────────────────────────
  {
    id: "a50",
    name: "Galaxy A50",
    year: 2020,
    price: 1999,
    chipset: "Exynos 9610",
    display: "6.4\" Super AMOLED, 60Hz",
    ram: "4GB",
    storage: "64GB",
    battery: "4000mAh",
    camera: "25MP + 8MP + 5MP",
    selfie: "25MP",
    fiveG: false,
    scores: { camera: 6, performance: 4, battery: 6, display: 7, value: 5 },
    verdict: "Skip It",
    verdictColor: "red",
    pros: ["AMOLED screen is still nice", "In-display fingerprint reader"],
    cons: ["Very slow Exynos 9610 now", "4000mAh ages poorly", "Much better options available"],
    mrPointSays: "The A50 had a good run but it is 2025. The Exynos 9610 makes it feel like running in mud. Even for free it will frustrate you. Unless you're in a real pinch, skip it."
  },
  {
    id: "a12",
    name: "Galaxy A12",
    year: 2020,
    price: 1499,
    chipset: "MediaTek Helio P35",
    display: "6.5\" PLS LCD, 60Hz",
    ram: "3GB",
    storage: "32GB",
    battery: "5000mAh",
    camera: "48MP + 5MP + 2MP + 2MP",
    selfie: "8MP",
    fiveG: false,
    scores: { camera: 4, performance: 3, battery: 7, display: 3, value: 4 },
    verdict: "Avoid",
    verdictColor: "red",
    pros: ["5000mAh battery", "Cheap"],
    cons: ["Helio P35 is one of the worst chips Samsung used", "LCD screen looks terrible", "3GB RAM is painful"],
    mrPointSays: "The A12 was Samsung's worst value phone in years. They shipped a terrible chip in a budget bracket and expected people to be happy. The battery lasts but everything else is a chore. Avoid at all costs."
  }
];

// Score label helper
function getScoreLabel(score) {
  if (score >= 9)   return { label: "Must Buy",    color: "#16a34a" };
  if (score >= 7.5) return { label: "Great Buy",   color: "#22c55e" };
  if (score >= 6.5) return { label: "Good Pick",   color: "#84cc16" };
  if (score >= 5.5) return { label: "Decent",      color: "#eab308" };
  if (score >= 4.5) return { label: "Think Twice", color: "#f97316" };
  if (score >= 3)   return { label: "Skip It",     color: "#ef4444" };
  return               { label: "Avoid",       color: "#b91c1c" };
}

// Calculate overall score
function getOverallScore(scores) {
  const vals = Object.values(scores);
  return Math.round((vals.reduce((a, b) => a + b, 0) / vals.length) * 10) / 10;
}

// Enrich phones with overall score
phones.forEach(p => {
  p.brand = p.brand || "Samsung";
  p.overall = getOverallScore(p.scores);
  p.scoreInfo = getScoreLabel(p.overall);
});
