const laptops = [

  // ── BUDGET (Under R10,000) ────────────────────────────────────────────────
  {
    id: "hp-255-g9",
    name: "HP 255 G9",
    brand: "HP",
    year: 2024,
    price: 6999,
    category: "Budget",
    cpu: "AMD Ryzen 5 5625U",
    gpu: "AMD Radeon (Integrated)",
    display: "15.6\" FHD IPS, 60Hz",
    ram: "8GB DDR4",
    storage: "256GB SSD",
    battery: "41Wh (~6hrs)",
    weight: "1.74kg",
    os: "Windows 11 Home",
    scores: { performance: 6, display: 6, battery: 6, build: 6, value: 8 },
    pros: ["Solid Ryzen 5 performance for the price", "Lightweight and portable", "Good value for students"],
    cons: ["256GB storage fills up fast", "Plastic build feels cheap", "Screen could be brighter"],
    mrPointSays: "The HP 255 G9 is a capable student laptop that won't break the bank. The Ryzen 5 5625U handles office work and light tasks well. Just upgrade to a 512GB SSD if you can — 256GB runs out quickly."
  },
  {
    id: "acer-aspire-3-a315",
    name: "Acer Aspire 3 A315",
    brand: "Acer",
    year: 2024,
    price: 7499,
    category: "Budget",
    cpu: "AMD Ryzen 5 5500U",
    gpu: "AMD Radeon (Integrated)",
    display: "15.6\" FHD IPS, 60Hz",
    ram: "8GB DDR4",
    storage: "512GB SSD",
    battery: "50Wh (~7hrs)",
    weight: "1.90kg",
    os: "Windows 11 Home",
    scores: { performance: 6, display: 6, battery: 7, build: 5, value: 8 },
    pros: ["512GB storage is generous at this price", "Good battery life", "Affordable and reliable"],
    cons: ["Build quality feels plasticky", "Screen has low brightness", "No backlit keyboard"],
    mrPointSays: "The Aspire 3 is the classic budget laptop. Nothing exciting about it but it just works. The 512GB SSD and decent battery life make it the best pick at this price range for anyone who just needs a laptop that does the job."
  },
  {
    id: "lenovo-ideapad-slim-3",
    name: "Lenovo IdeaPad Slim 3",
    brand: "Lenovo",
    year: 2024,
    price: 7999,
    category: "Budget",
    cpu: "AMD Ryzen 5 7520U",
    gpu: "AMD Radeon (Integrated)",
    display: "15.6\" FHD IPS, 60Hz",
    ram: "8GB LPDDR5",
    storage: "512GB SSD",
    battery: "45Wh (~8hrs)",
    weight: "1.62kg",
    os: "Windows 11 Home",
    scores: { performance: 7, display: 6, battery: 8, build: 6, value: 8 },
    verdict: "Good Pick",
    pros: ["Ryzen 7520U is surprisingly efficient", "Great battery life for the price", "Light and portable"],
    cons: ["Screen is dim and colour-inaccurate", "Only 8GB RAM (not upgradeable on some models)", "Speakers are weak"],
    mrPointSays: "The IdeaPad Slim 3 punches above its weight. The Ryzen 7520U keeps things snappy without killing the battery, and at under R8000 with 512GB storage it's genuinely good value. The screen is its biggest weakness."
  },

  // ── MID-RANGE (R10,000–R20,000) ───────────────────────────────────────────
  {
    id: "asus-vivobook-15",
    name: "ASUS VivoBook 15",
    brand: "ASUS",
    year: 2024,
    price: 10999,
    category: "Mid-Range",
    cpu: "AMD Ryzen 5 5600H",
    gpu: "AMD Radeon (Integrated)",
    display: "15.6\" FHD IPS, 144Hz",
    ram: "8GB DDR4",
    storage: "512GB SSD",
    battery: "50Wh (~6hrs)",
    weight: "1.80kg",
    os: "Windows 11 Home",
    scores: { performance: 7, display: 7, battery: 6, build: 7, value: 8 },
    pros: ["144Hz display is smooth for the price", "Ryzen 5 5600H is fast", "Good keyboard feel"],
    cons: ["Battery doesn't last long under load", "Gets warm with heavy tasks", "Only 8GB RAM"],
    mrPointSays: "The VivoBook 15 stands out with its 144Hz panel at this price — everything feels smoother from browsing to gaming. The Ryzen 5 5600H handles most tasks confidently. Battery life is the trade-off. Good mid-range buy."
  },
  {
    id: "hp-pavilion-15",
    name: "HP Pavilion 15",
    brand: "HP",
    year: 2024,
    price: 11999,
    category: "Mid-Range",
    cpu: "AMD Ryzen 7 5700U",
    gpu: "AMD Radeon (Integrated)",
    display: "15.6\" FHD IPS, 60Hz",
    ram: "16GB DDR4",
    storage: "512GB SSD",
    battery: "43Wh (~7hrs)",
    weight: "1.76kg",
    os: "Windows 11 Home",
    scores: { performance: 7, display: 6, battery: 7, build: 7, value: 7 },
    pros: ["16GB RAM handles multitasking well", "Ryzen 7 is fast for everyday work", "Premium look and feel for the price"],
    cons: ["60Hz screen feels behind competitors", "Battery is small for the price", "Gets warm during extended use"],
    mrPointSays: "The Pavilion 15 with 16GB RAM is a solid productivity machine. The Ryzen 7 5700U keeps things snappy and the extra RAM means you can have 30 tabs open without slowdown. The 60Hz screen is the main letdown at this price."
  },
  {
    id: "dell-inspiron-15",
    name: "Dell Inspiron 15 3520",
    brand: "Dell",
    year: 2024,
    price: 12999,
    category: "Mid-Range",
    cpu: "Intel Core i5-1235U (12th Gen)",
    gpu: "Intel Iris Xe (Integrated)",
    display: "15.6\" FHD WVA, 120Hz",
    ram: "16GB DDR4",
    storage: "512GB SSD",
    battery: "54Wh (~9hrs)",
    weight: "1.65kg",
    os: "Windows 11 Home",
    scores: { performance: 7, display: 7, battery: 8, build: 7, value: 8 },
    pros: ["Excellent battery life", "120Hz display is smooth", "Solid build and light weight"],
    cons: ["Intel Xe graphics limit gaming", "Gets slightly warm under load", "No dedicated GPU option"],
    mrPointSays: "The Dell Inspiron 3520 is one of the best all-round mid-range laptops you can buy right now. Great battery, smooth 120Hz screen, solid build and 16GB RAM — all under R13,000. If you're not gaming, this is the one to get."
  },
  {
    id: "lenovo-ideapad-5",
    name: "Lenovo IdeaPad 5",
    brand: "Lenovo",
    year: 2024,
    price: 14999,
    category: "Mid-Range",
    cpu: "AMD Ryzen 7 5700U",
    gpu: "AMD Radeon (Integrated)",
    display: "15.6\" FHD IPS, 60Hz",
    ram: "16GB DDR4",
    storage: "512GB SSD",
    battery: "56Wh (~10hrs)",
    weight: "1.67kg",
    os: "Windows 11 Home",
    scores: { performance: 8, display: 7, battery: 9, build: 8, value: 7 },
    pros: ["Exceptional battery life", "Premium aluminium build", "Fast Ryzen 7 performance"],
    cons: ["60Hz screen at this price is disappointing", "No dedicated GPU", "Pricier than competitors with similar specs"],
    mrPointSays: "The IdeaPad 5 is the most premium-feeling laptop in this price range. The aluminium chassis, great battery and Ryzen 7 chip make it a joy for daily use. The 60Hz screen is the only real complaint."
  },

  // ── GAMING ────────────────────────────────────────────────────────────────
  {
    id: "lenovo-ideapad-gaming-3",
    name: "Lenovo IdeaPad Gaming 3",
    brand: "Lenovo",
    year: 2024,
    price: 15999,
    category: "Gaming",
    cpu: "AMD Ryzen 5 7535HS",
    gpu: "NVIDIA GeForce RTX 3050",
    display: "15.6\" FHD IPS, 120Hz",
    ram: "8GB DDR5",
    storage: "512GB SSD",
    battery: "45Wh (~4hrs gaming)",
    weight: "2.20kg",
    os: "Windows 11 Home",
    scores: { performance: 7, display: 7, battery: 5, build: 6, value: 8 },
    pros: ["RTX 3050 handles 1080p gaming well", "Ryzen 7535HS is fast", "Good price for a gaming laptop"],
    cons: ["Battery dies fast during gaming", "Gets hot under sustained load", "Plastic build isn't premium"],
    mrPointSays: "The IdeaPad Gaming 3 is the go-to entry-level gaming laptop in SA. The RTX 3050 plays most games at 1080p medium-high settings smoothly. Just know you'll need to be plugged in — gaming battery life is about 2-3 hours."
  },
  {
    id: "acer-nitro-5",
    name: "Acer Nitro 5",
    brand: "Acer",
    year: 2024,
    price: 17999,
    category: "Gaming",
    cpu: "Intel Core i5-12500H",
    gpu: "NVIDIA GeForce RTX 3050",
    display: "15.6\" FHD IPS, 144Hz",
    ram: "16GB DDR4",
    storage: "512GB SSD",
    battery: "57Wh (~4hrs gaming)",
    weight: "2.30kg",
    os: "Windows 11 Home",
    scores: { performance: 8, display: 7, battery: 5, build: 7, value: 7 },
    pros: ["16GB RAM + 144Hz display is a great combo", "Solid gaming performance", "Easy to upgrade RAM and SSD"],
    cons: ["Heavy and chunky", "Very loud fans at full load", "Gaming battery life is poor"],
    mrPointSays: "The Nitro 5 is a proven gaming laptop that's easy to recommend. 144Hz screen, 16GB RAM and solid cooling mean it handles games well. It's loud and hot under pressure but that's expected at this price. A reliable choice."
  },
  {
    id: "asus-tuf-gaming-a15",
    name: "ASUS TUF Gaming A15",
    brand: "ASUS",
    year: 2024,
    price: 18999,
    category: "Gaming",
    cpu: "AMD Ryzen 7 7435HS",
    gpu: "NVIDIA GeForce RTX 4050",
    display: "15.6\" FHD IPS, 144Hz",
    ram: "16GB DDR5",
    storage: "512GB SSD",
    battery: "90Wh (~6hrs light use)",
    weight: "2.20kg",
    os: "Windows 11 Home",
    scores: { performance: 9, display: 7, battery: 7, build: 8, value: 8 },
    pros: ["RTX 4050 is a massive step up for gaming", "Better-than-expected battery for a gaming laptop", "MIL-SPEC durability rating"],
    cons: ["Heavy to carry around", "Screen lacks colour accuracy for creative work", "Gets warm during sustained gaming"],
    mrPointSays: "The TUF A15 with RTX 4050 is the best gaming laptop under R20,000 right now. The RTX 4050 destroys the RTX 3050 in gaming performance, the battery is surprisingly decent, and the build is genuinely tough. Highly recommended."
  },

  // ── PREMIUM ───────────────────────────────────────────────────────────────
  {
    id: "macbook-air-m2",
    name: "MacBook Air M2",
    brand: "Apple",
    year: 2023,
    price: 27999,
    category: "Premium",
    cpu: "Apple M2 (8-core CPU)",
    gpu: "Apple M2 (8-core GPU)",
    display: "13.6\" Liquid Retina, 60Hz",
    ram: "8GB Unified Memory",
    storage: "256GB SSD",
    battery: "52.6Wh (~15hrs)",
    weight: "1.24kg",
    os: "macOS",
    scores: { performance: 9, display: 9, battery: 10, build: 10, value: 7 },
    pros: ["Insane battery life — genuinely 15+ hours", "Fanless design runs completely silent", "Best-in-class build quality"],
    cons: ["256GB fills up fast — consider upgrading", "60Hz screen in 2024 is behind competitors", "macOS takes getting used to if you're switching"],
    mrPointSays: "The MacBook Air M2 remains one of the best laptops ever made. The combination of battery life, build quality and silence is unmatched. Just buy the 512GB version — 256GB is too little. If you're on macOS, this is the benchmark."
  },
  {
    id: "macbook-air-m3",
    name: "MacBook Air M3",
    brand: "Apple",
    year: 2024,
    price: 32999,
    category: "Premium",
    cpu: "Apple M3 (8-core CPU)",
    gpu: "Apple M3 (10-core GPU)",
    display: "13.6\" Liquid Retina, 60Hz",
    ram: "8GB Unified Memory",
    storage: "256GB SSD",
    battery: "52.6Wh (~18hrs)",
    weight: "1.24kg",
    os: "macOS",
    scores: { performance: 10, display: 9, battery: 10, build: 10, value: 7 },
    pros: ["M3 chip is blazing fast", "Even better battery than M2", "Supports two external displays now"],
    cons: ["Very expensive in SA", "Still 60Hz display", "256GB base storage is stingy at this price"],
    mrPointSays: "The MacBook Air M3 is the best laptop money can buy right now, full stop. The M3 chip makes everything feel instant, the battery genuinely lasts all day and then some, and the build is flawless. The price stings in SA but it's worth every rand if you can stretch to it."
  },
  {
    id: "dell-xps-13",
    name: "Dell XPS 13 Plus",
    brand: "Dell",
    year: 2024,
    price: 29999,
    category: "Premium",
    cpu: "Intel Core i7-1360P (13th Gen)",
    gpu: "Intel Iris Xe (Integrated)",
    display: "13.4\" FHD+ OLED, 60Hz",
    ram: "16GB LPDDR5",
    storage: "512GB SSD",
    battery: "55Wh (~9hrs)",
    weight: "1.26kg",
    os: "Windows 11 Pro",
    scores: { performance: 8, display: 10, battery: 7, build: 9, value: 6 },
    pros: ["OLED display is absolutely stunning", "Incredibly thin and premium build", "Powerful Core i7 performance"],
    cons: ["Expensive for integrated graphics only", "Gets warm quickly under load", "Limited port selection"],
    mrPointSays: "The XPS 13 Plus has the best screen of any Windows laptop — that OLED panel is genuinely breathtaking. But R30,000 for integrated graphics is hard to justify. It's a beautiful machine for creative professionals and executives who want the best-looking Windows laptop."
  },
];

// Score categories for laptops
const laptopScoreCategories = [
  { key: 'performance', label: 'Performance', icon: '⚡' },
  { key: 'display',     label: 'Display',     icon: '🖥️' },
  { key: 'battery',     label: 'Battery',     icon: '🔋' },
  { key: 'build',       label: 'Build',       icon: '🔨' },
  { key: 'value',       label: 'Value',       icon: '💰' },
];

// Reuse same score helpers
laptops.forEach(l => {
  const vals = Object.values(l.scores);
  l.overall = Math.round((vals.reduce((a, b) => a + b, 0) / vals.length) * 10) / 10;
  l.scoreInfo = getScoreLabel(l.overall);
});
